<a href="https://colab.research.google.com/github/jyothi1235/Chandigarh-Ladakh-Election-Analysis/blob/main/Iris_Training_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
from sklearn.datasets import load_iris

In [44]:
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader

In [24]:
import torch
import torch.nn as nn
import torch.optim as optim

In [25]:
dt = load_iris()

In [26]:
dt.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [27]:
X, Y = dt.data, dt.target

In [28]:
dt.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [29]:
model = nn.Sequential(
    nn.Linear(4, 30),
    nn.ReLU(),
    nn.Linear(30, 10),
    nn.ReLU(),
    nn.Linear(10, 3),
    # nn.Softmax(dim=1)
)

In [30]:
X = torch.FloatTensor(X)
Y = torch.LongTensor(Y)

In [31]:
model(X)

tensor([[ 1.0129e-01, -4.3456e-01, -7.7510e-02],
        [ 1.1099e-01, -4.0539e-01, -9.1236e-02],
        [ 9.9148e-02, -3.9443e-01, -9.3910e-02],
        [ 1.0967e-01, -3.8557e-01, -8.7464e-02],
        [ 9.7060e-02, -4.3197e-01, -7.6389e-02],
        [ 1.0936e-01, -4.7309e-01, -5.0804e-02],
        [ 9.6804e-02, -3.9681e-01, -8.5579e-02],
        [ 1.0708e-01, -4.2325e-01, -7.5487e-02],
        [ 1.0656e-01, -3.6664e-01, -9.9104e-02],
        [ 1.1306e-01, -4.0757e-01, -8.3492e-02],
        [ 1.0464e-01, -4.6358e-01, -6.4364e-02],
        [ 1.1015e-01, -4.0866e-01, -7.3700e-02],
        [ 1.0918e-01, -3.9748e-01, -9.1725e-02],
        [ 8.9684e-02, -3.5785e-01, -1.1315e-01],
        [ 8.9747e-02, -5.0393e-01, -7.0238e-02],
        [ 9.0827e-02, -5.1548e-01, -4.6940e-02],
        [ 9.1376e-02, -4.7374e-01, -7.2218e-02],
        [ 1.0163e-01, -4.3533e-01, -7.8056e-02],
        [ 1.1575e-01, -4.8885e-01, -4.8781e-02],
        [ 9.7735e-02, -4.4805e-01, -6.5924e-02],
        [ 1.2244e-01

In [32]:
torch.argmax(model(X), dim=1)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0])

In [33]:
lossfn = nn.CrossEntropyLoss()
optSgd = optim.SGD(model.parameters(), lr=0.01)

In [34]:

for _ in range(200):
    optSgd.zero_grad()
    Yp = model(X)
    loss = lossfn(Yp, Y)
    loss.backward()
    optSgd.step()

    print(loss.item())

1.162595272064209
1.1520936489105225
1.1426188945770264
1.1340030431747437
1.1261035203933716
1.1188175678253174
1.1120375394821167
1.1056751012802124
1.0997121334075928
1.0941029787063599
1.0888025760650635
1.0837715864181519
1.078967571258545
1.0743621587753296
1.069922685623169
1.0656639337539673
1.0615466833114624
1.0575239658355713
1.0535943508148193
1.049743413925171
1.0459197759628296
1.0420180559158325
1.0381028652191162
1.0341647863388062
1.0301510095596313
1.0261898040771484
1.0223057270050049
1.0185139179229736
1.0148005485534668
1.0111535787582397
1.007633924484253
1.0043954849243164
1.0015047788619995
0.9988407492637634
0.9962375164031982
0.9936700463294983
0.9911123514175415
0.9885677099227905
0.9860244989395142
0.9834820628166199
0.9809391498565674
0.9783946871757507
0.9758486747741699
0.9732998609542847
0.9707481861114502
0.9681887030601501
0.9656206369400024
0.9630449414253235
0.9604673385620117
0.9579155445098877
0.9553497433662415
0.9527702927589417
0.950205862522125

In [35]:
for _ in range(100):
    optSgd.zero_grad()
    Yp = model(X)
    loss = lossfn(Yp, Y)
    loss.backward()
    optSgd.step()

    print(loss.item())

0.5978754758834839
0.5957738757133484
0.5936864614486694
0.5916127562522888
0.5895542502403259
0.5875101089477539
0.585480272769928
0.5834652185440063
0.5814646482467651
0.579477846622467
0.5775058269500732
0.5755486488342285
0.573606014251709
0.5716776251792908
0.569763720035553
0.5678641200065613
0.5659784078598022
0.5641071796417236
0.5622503757476807
0.5604076385498047
0.5585787892341614
0.5567641258239746
0.5549632906913757
0.5531771779060364
0.5514046549797058
0.5496459603309631
0.5479006171226501
0.5461685657501221
0.5444498062133789
0.5427441596984863
0.54105144739151
0.5393714904785156
0.5377042889595032
0.5360502600669861
0.5344088077545166
0.5327800512313843
0.5311638116836548
0.5295602679252625
0.5279723405838013
0.526403546333313
0.5248464345932007
0.5233010649681091
0.521767258644104
0.5202451348304749
0.5187339782714844
0.517233669757843
0.5157443881034851
0.5142667889595032
0.5128106474876404
0.511365532875061
0.509931206703186
0.5085071921348572
0.5070935487747192
0.50

In [36]:
model(X)

tensor([[ 1.7714, -0.6302, -1.7175],
        [ 1.5383, -0.5164, -1.5483],
        [ 1.6583, -0.5697, -1.6216],
        [ 1.4646, -0.4767, -1.4936],
        [ 1.7749, -0.6317, -1.7202],
        [ 1.7908, -0.6496, -1.7513],
        [ 1.6548, -0.5703, -1.6206],
        [ 1.6791, -0.5839, -1.6507],
        [ 1.4204, -0.4522, -1.4519],
        [ 1.5191, -0.5039, -1.5400],
        [ 1.8472, -0.6709, -1.7819],
        [ 1.5626, -0.5267, -1.5712],
        [ 1.5417, -0.5128, -1.5463],
        [ 1.5931, -0.5313, -1.5635],
        [ 2.0224, -0.7650, -1.9307],
        [ 2.0171, -0.7689, -1.9317],
        [ 1.8964, -0.7031, -1.8284],
        [ 1.7598, -0.6272, -1.7103],
        [ 1.7907, -0.6514, -1.7614],
        [ 1.8050, -0.6514, -1.7486],
        [ 1.5500, -0.5308, -1.5896],
        [ 1.7732, -0.6371, -1.7238],
        [ 1.7702, -0.6294, -1.7164],
        [ 1.4107, -0.4690, -1.4884],
        [ 1.2847, -0.3991, -1.4040],
        [ 1.3710, -0.4402, -1.4509],
        [ 1.5583, -0.5330, -1.5771],
 

In [37]:
Ynewp=model(X)


In [39]:
sftout=torch.softmax(Ynewp,dim=1)

In [40]:
torch.argmax(sftout,dim=1)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1,
        2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1,
        1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2])

In [42]:
data = torch.cat((X, Y.unsqueeze(1)), dim=1)

In [43]:
batches=DataLoader(data,batch_size=10,shuffle=True)

NameError: name 'DataLoader' is not defined

In [40]:
for batch in batches:
  X=batch[:,:-1]
  Y=batch[:,-1]

